# Setup
title       : RD Packages
tagline     : 'RD Software Packages'
description : 'Regression Discontinuity Designs Software Packages'
keywords    : "regression discontinuity designs, program evaluation, causal inference, treatment effects, R, Stata"
url         : https://rdpackages.github.io
baseurl     : https://rdpackages.github.io
paginate    : 5


# About and contact
author:
  name:           
  url:            

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
